# Generated by Django 4.2 on 2025-10-22 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodplan_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dailymenu',
            options={'verbose_name': 'Дневное меню', 'verbose_name_plural': 'Дневные меню'},
        ),
        migrations.AlterModelOptions(
            name='foodtag',
            options={'verbose_name': 'Тег еды', 'verbose_name_plural': 'Теги еды'},
        ),
        migrations.AlterModelOptions(
            name='ingredient',
            options={'verbose_name': 'Ингредиент', 'verbose_name_plural': 'Ингредиенты'},
        ),
        migrations.AlterModelOptions(
            name='menutype',
            options={'verbose_name': 'Тип меню', 'verbose_name_plural': 'Типы меню'},
        ),
        migrations.AlterModelOptions(
            name='pricerange',
            options={'verbose_name': 'Диапазон цен', 'verbose_name_plural': 'Диапазоны цен'},
        ),
        migrations.AlterModelOptions(
            name='recipe',
            options={'verbose_name': 'Рецепт', 'verbose_name_plural': 'Рецепты'},
        ),
        migrations.AlterModelOptions(
            name='recipeingredient',
            options={'verbose_name': 'Ингредиент рецепта', 'verbose_name_plural': 'Ингредиенты рецептов'},
        ),
        migrations.AlterModelOptions(
            name='subscription',
            options={'ordering': ['user', 'menu_type'], 'verbose_name': 'Подписка', 'verbose_name_plural': 'Подписки'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'Пользователь', 'verbose_name_plural': 'Пользователи'},
        ),
        migrations.AlterModelOptions(
            name='userpage',
            options={'ordering': ['username'], 'verbose_name': 'Страница клиента', 'verbose_name_plural': 'Страницы клиентов'},
        ),
        migrations.AddField(
            model_name='ingredient',
            name='allergens',
            field=models.ManyToManyField(blank=True, related_name='ingredients', to='foodplan_app.foodtag', verbose_name='Аллергены'),
        ),
    ]
