# Generated by Django 4.2 on 2025-10-22 21:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodplan_app', '0002_alter_dailymenu_options_alter_foodtag_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='foodtag',
            options={'verbose_name': 'Аллерген', 'verbose_name_plural': 'Аллергены'},
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='tags',
        ),
    ]
