# Generated by Django 4.2 on 2025-10-22 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodplan_app', '0003_alter_foodtag_options_remove_recipe_tags'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subscription',
            options={'ordering': ['user'], 'verbose_name': 'Подписка', 'verbose_name_plural': 'Подписки'},
        ),
        migrations.RemoveField(
            model_name='dailymenu',
            name='menu_type',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='menu_type',
        ),
        migrations.RemoveField(
            model_name='subscription',
            name='menu_type',
        ),
        migrations.RemoveField(
            model_name='userpage',
            name='menu_type',
        ),
        migrations.AddField(
            model_name='dailymenu',
            name='menu_types',
            field=models.ManyToManyField(blank=True, related_name='dailymenus', to='foodplan_app.menutype', verbose_name='Типы меню'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='menu_types',
            field=models.ManyToManyField(blank=True, related_name='recipes', to='foodplan_app.menutype', verbose_name='Типы меню'),
        ),
        migrations.AddField(
            model_name='subscription',
            name='menu_types',
            field=models.ManyToManyField(blank=True, related_name='subscriptions', to='foodplan_app.menutype', verbose_name='Типы меню'),
        ),
        migrations.AddField(
            model_name='userpage',
            name='menu_types',
            field=models.ManyToManyField(blank=True, related_name='users', to='foodplan_app.menutype', verbose_name='Типы меню'),
        ),
    ]
